### ISSUE TITLE
BlenderProc

### ISSUE THREAD

**Issue by themasterlink** [boschresearch/amira_blender_rendering#1]
I love this project! I think it is really important that more and more people join in in the effort of creating realistic data for deep learning. 

It is so similar to our own work: https://github.com/DLR-RM/BlenderProc

Could you point me to an outlook what features are coming to this project, as we are always looking for ways of improving our own extensive library. And also do you plan to support common datasets like ShapeNet or SceneNet? See our examples for reference: https://github.com/DLR-RM/BlenderProc/tree/master/examples

**Comment by MarcoTodescato** [comment]
Hi there @themasterlink ,

we really appreciate your interest in ABR. We also looked into your amazing BlenderProc project.

It would be great to understand synergies and look for collaborations ;-)

Currently, I cannot point you to an outlook regarding upcoming features. However, we are currently not planning to actively support specific datasets.
I will definitely keep you posted on major updates as soon as they'll be available.

**Comment by themasterlink** [comment]
Hey @MarcoTodescato 

thanks for the praise! 

I am looking forward to seeing the next steps this project will take!
