### ISSUE TITLE
data preparation documentation

### ISSUE THREAD

**Issue by yoel-bosch** [boschresearch/amira_blender_rendering#17]
on behalf of QIU Xuchong (CR/RIX-AP)

the documentation for data preparation is outdated, causing the example to fail
in particular it misses instructions for which targets to "dvc pull"

**Comment by MarcoTodescato** [comment]
Hi @yoel-bcai ,

this is a very good point. Just to be sure I understand this correctly, you (aka QUI) do not find documentation on how to download assets in order to populate the existing scenes. Correct?

The issue is that we have not found yet a public space where to put such assets and I would refrain from putting documentation related to our internal data storage.

Bottom line, I am not sure we can fix this atm.

But if you have a different opinion, we can discuss about it ;-)

**Comment by yoel-bosch** [comment]
Hi, welcome back! 🤗

Yes, Xuchong couldn’t run the example because of data being elsewhere

I think the solution would be to clear 1-2 items, add them to git repo, and adjust example to use them

Btw - do you have a video for ABR that we could present on a flatscreen in our booth at the IMVC conference?

Sent from my iPhone

On 17 Sep 2021, at 10:01, Marco Todescato ***@***.***> wrote:

﻿

Hi @yoel-bcai<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyoel-bcai&data=04%7C01%7Cyoel.shapiro%40bosch.com%7C54b89b2e28a44448b55f08d979a8f32c%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637674588814173367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gIeDgXB0vcDLY6yoo8KwcYnpnLgV5COUN3F448SpD%2Fw%3D&reserved=0> ,

this is a very good point. Just to be sure I understand this correctly, you (aka QUI) do not find documentation on how to download assets in order to populate the existing scenes. Correct?

The issue is that we have not found yet a public space where to put such assets and I would refrain from putting documentation related to our internal data storage.

Bottom line, I am not sure we can fix this atm.

But if you have a different opinion, we can discuss about it ;-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fboschresearch%2Famira_blender_rendering%2Fissues%2F17%23issuecomment-921549415&data=04%7C01%7Cyoel.shapiro%40bosch.com%7C54b89b2e28a44448b55f08d979a8f32c%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637674588814173367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2bkcDjpIBqJBE6D1QvCLGd9mu3PTaeWNKEGT2UBvDTA%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUKIZ57IXK3I5GYBQWSFKRLUCLRT5ANCNFSM476UUP3A&data=04%7C01%7Cyoel.shapiro%40bosch.com%7C54b89b2e28a44448b55f08d979a8f32c%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637674588814183313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cbD1sIJYt4G56%2FKTxD%2BAWXK86uWytU6ndqGTjLnBnwM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cyoel.shapiro%40bosch.com%7C54b89b2e28a44448b55f08d979a8f32c%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637674588814183313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5fiwPGduZ0CUjbuCXetMZyp1UItEKasF8hrjUqhP8q0%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cyoel.shapiro%40bosch.com%7C54b89b2e28a44448b55f08d979a8f32c%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637674588814183313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kwFTGWh1LqMa6%2FsCcT9BZ%2BWGcDhueLJ1Yl67bLn3jbw%3D&reserved=0>.

**Comment by MarcoTodescato** [comment]
clearing some items and creating a dedicated example might be a good idea.

Regarding ABR video, the best we have atm and that we usually use is the .gif you can find in /media folder

**Comment by MarcoTodescato** [comment]
@yoel-bosch I added few data files and a new "intro" tutorial that you should be able to find in the documentation. I thing this should be enough for the moment. Clearing more .ply might require more effort.
